#!/usr/bin/env bash
# This script is transferring a file from our client to a server

if [ $# -le 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi

# assigning the paraments to its vars..

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# disabling the strict host key of checking ..
scp -o "stricthostkeychecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checing if the operation of transfer is successful
if [ $=? -eq 0 ]
then
echo "Yas-file-X transferred SUCSESS"
else
echo "Yas-file-X FAILED"
fi
