#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
sudo apt-get update -y
sudo apt-get install curl -y
sudo apt-get install nginx -y
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i 's/listen 8080 default_server;.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on;.*/listen \[::\]:80 default_server;/' /etc/nginx/sites-enabled/default
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
