#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
# test nginx
sudo nginx -t
sudo service nginx restart
