#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt-get update
sudo apt install haproxy=2.4.\*

variables="\tbind :80\n\tmode http\n\tdefault_backend servers\nbackend servers\n\tbalance roundrobin\n\tserver 186857-web-01 34.204.61.214:80 check\n\tserver 186857-web-02 18.206.202.174:80 check"

sudo sed -i "/errorfile 504/a frontend yas-adv.tech" /etc/haproxy/haproxy.cfg
sudo sed -i "/frontend yas-adv.tech/a $variables" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
