#!/usr/bin/env bash
# This script lists all processes running in the system

# Use the `ps` command to display information about processes in the system
# The `-a` option displays information about all processes, not just those associated with the current terminal
# The `-u` option displays the processes owned by the user that executed the `ps` command
# The `-x` option displays information about processes that are not associated with a terminal
# The `-f` option displays a full listing of the processes, including additional information such as the parent process ID (PPID) and CPU usage
ps -auxf
