#!/usr/bin/env bash
# Create a PID file for the script
# Print a message repeatedly
# Print a message when receiving a SIGINT signal
# Print a message and terminate the script when receiving a SIGTERM signal
# Terminate the script when receiving a SIGQUIT signal and remove the PID file

echo "$$" > /var/run/myscript.pid

# Define a function to remove the PID file and exit
termfunc() {
    rm /var/run/myscript.pid
    exit
}

# Loop indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 2
    # Print a message when receiving a SIGINT signal
    trap 'echo "Y U no love me?!"' SIGINT
    # Print a message and terminate the script when receiving a SIGTERM signal
    trap 'echo "I hate the kill command" && termfunc' SIGTERM
    # Terminate the script when receiving a SIGQUIT signal and remove the PID file
    trap 'termfunc' SIGQUIT
done
