#!/usr/bin/env bash
# Script to print a message every 2 seconds
# until manually interrupted or terminated.

while true; # loop indefinitely
do
	echo "To infinity and beyond"; # print the message
	sleep 2 # wait for 2 seconds
done # end of loop
