#!/usr/bin/env bash
# Bash script to terminate an infinite program using SIGTERM signal

# Find the process ID (PID) of the infinite program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Send the SIGTERM signal to the process with the given PID
if [ -n "$id" ]
then
  kill -15 "$id"
fi
