#!/usr/bin/env bash
# Script to stop the "4-to_infinity_and_beyond" program with SIGKILL signal.

# Find and terminate the infinite program by its command line.
pkill -15 "bash ./4-to_infinity_and_beyond" -f
