#!/usr/bin/env bash
# This script prints a message repeatedly, until it is manually stopped.
# The message is "To infinity and beyond".

# Handle SIGTERM signal (sent when script is terminated)
trap "echo 'I am invincible!!!'" 15

# Continuously print the message
while true;
do
    echo "To infinity and beyond";
    sleep 2; # Pause for 2 seconds between each message
done
