#!/usr/bin/env bash
# Script to kill the '7-highlander' program using the SIGKILL signal

# Use 'pkill' command to forcefully stop the process named 'bash ./7-highlander'
pkill -9 "bash ./7-highlander" -f
