#!/usr/bin/env bash
# Creates a file and writes "I am alive!" to it every 2 seconds

FILE_PATH=/tmp/my_process
sudo touch $FILE_PATH

while true; do
    sudo bash -c "echo \"I am alive!\" >> $FILE_PATH"
    sleep 2
done
