#!/usr/bin/env bash

# A script that reads and displays user information from the /etc/passwd file with a fun and unique twist.

while IFS=: read -r user_info
do
    # Extract the relevant fields from the user_info using the delimiter ':' and assign them to variables.
    USERNAME=$(echo "$user_info" | cut -f 1 -d ':')
    PASSWORD=$(echo "$user_info" | cut -f 2 -d ':')
    USER_ID=$(echo "$user_info" | cut -f 3 -d ':')
    GROUP_ID=$(echo "$user_info" | cut -f 4 -d ':')
    USER_INFO=$(echo "$user_info" | cut -f 5 -d ':')
    HOME_DIR=$(echo "$user_info" | cut -f 6 -d ':')
    COMMAND=$(echo "$user_info" | cut -f 7 -d ':')

    # Display the user information in a unique and humorous way.
    echo -n "Introducing $USERNAME of the $GROUP_ID gang, "
    echo -n "who calls $HOME_DIR home and cruises on $COMMAND. "
    echo -n "Their security is tight thanks to passcode $PASSWORD, "
    echo "and for more details, consult $USER_INFO."

done < "/etc/passwd"
