#!/usr/bin/env bash
# Use awk to extract IP address and HTTP status code from Apache access log.
# Print the first (IP address) and ninth (HTTP status code) columns of the log file.
awk '{ print $1, $9}' apache-access.log
