#!/usr/bin/env bash
# This Bash script prints "Best School" 10 times with some variations

# Initialize counter variable
counter=1

# Loop 10 times
while [ $counter -le 10 ]
do
    if [[ $counter == '4' ]]
    then
        # Print "bad luck" instead of "Best School" on the 4th iteration
        echo "bad luck"
    elif [[ $counter == '8' ]]
    then
        # Print "good luck" instead of "Best School" on the 8th iteration
        echo "good luck"
    else
        # Print "Best School" on all other iterations
        echo "Best School"
    fi
    # Increment counter variable
    ((counter++))
done
